### PR TITLE
Fix for long computer names

### LINKED ISSUE #113: Error: Skip computer 'x' with new name 'x' because the new name is the same as the current name.
##### SUMMARY
The `microsoft.ad.membership` fails if the computer name is longer than 15 characters.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
microsoft.ad.membership

##### ANSIBLE VERSION

```paste below
2.9.27
```

##### COLLECTION VERSION

```paste below
microsoft.ad:1.5.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Windows 10.

##### STEPS TO REPRODUCE
Join a computer to a domain using the following task. Use a computer name that is longer than 15 characters:

```yaml
    - name: Join AD domain
      microsoft.ad.membership:
        dns_domain_name: "test.local"
        domain_admin_user: "{{ domain_admin_user}}"
        domain_admin_password: "{{ domain_admin_password }}"
        hostname: "my-long-computer-name"
        state: "domain"
        reboot: true
```

##### EXPECTED RESULTS
The step should succeed without changes because of idempotency.

##### ACTUAL RESULTS
```paste below
Run: [2024-04-24 22:56:39,277][INFO][CMD]: TASK [ad-joined : Join AD domain]  **********************************************
Run: [2024-04-24 22:56:42,784][INFO][CMD]: fatal: [workstation] FAILED! => {"changed": false, "msg": "Skip computer 'my-long-computer-name' with new name 'my-long-computer-name' because the new name is the same as the current name.", "reboot_required": false}
Run: [2024-04-24 22:56:42,785][INFO][CMD]: 	to retry, use: --limit @/app/data/playbook.retry
```

### PR DESCRIPTION
**Pull request by aristotelos**
##### SUMMARY
Fix issue with long computer hostnames.

Fixes #113 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
microsoft.ad.membership

### CODE REVIEW

**Comment by jborean93** [comment]
Thanks for the PR, from a basic look I don't see this being a problem but I'll have to look a bit deeper as I seem to recall `GetHostName()` may have been problematic in some scenarios. I could have been thinking of another API so I'll have a play around and get back to you!

**Comment by jborean93** [comment]
I've opened https://github.com/aristotelos/microsoft.ad/pull/1 which contains the changelog fragment and changes to the existing manual tests to cover this new scenario. I've run them locally to ensure that this tests out your original issue as well as a few other edge cases to ensure we don't break it in the future.

I would probably recommend using `$cs.DNSHostName` and add `DNSHostName` to the `-Property` list on line 129 because:

+ It can retrieve Unicode characters, `GetHostName()` returns `?` for those characters
+ It doesn't rely on the socket API which may have issues depending on the OS setup (I could not find a way to break it though)

This isn't something you need to change so I left it alone in my PR targeting your branch but it might be worth considering when/if I ever get to adding Unicode support to this module.

**Comment by jterpstra1** [comment]
@jborean93 can a new release be published with this merge? 
We're running into the same issue and a new release with this would be appreciated.

Sorry for hijacking this issue.

**Comment by jborean93** [comment]
I'm hoping to merge in https://github.com/ansible-collections/microsoft.ad/pull/117 once it's ready before the next release. Hopefully it'll be out at the end of this week or next week.

**Pull request merged**
